on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  main:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.6.1
        with:
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          pull: true
          push: true
          no-cache: true
          tags: r3aper/jenkins:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
